# Generated by Django 5.1.3 on 2024-11-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField()),
                ('std_id', models.CharField(max_length=18)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.DateField()),
                ('tel', models.CharField(max_length=12)),
                ('batch', models.IntegerField()),
                ('major', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
