# Generated by Django 5.1.3 on 2024-12-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_student',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
