# Generated by Django 5.1.3 on 2024-12-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_data_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_student',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
